### ISSUE TITLE
Add a diagram type fragment to file extensions

### ISSUE THREAD

**Issue by prmr** [prmr/Violetta#15]

**Comment by prmr** [comment]
This issue used to be titled "Move to the Violet >0.16 serialization format" but after a bit of research it seems like the 0.16 and 0.21 formats are the same (JavaBean-enabled), the only difference being that in 0.21 the files get an additional extension fragment to indicate the diagram type.

**Comment by JoelChev** [comment]
@prmr I'm not sure if this helps with the problem at all, but I found a field marked "files.extension" in the UMLEditorStrings.properties file in the com.horstmann.violet package. Would modifying this field to a different extension do anything to fix this issue?

**Comment by prmr** [comment]
Worth a try indeed.

**Comment by JoelChev** [comment]
@prmr Ok. I will look at it. You just want a diagram type fragment added in front of the .violet extension depending on the type of diagram being saved right? So a Class diagram should now be saved as blahblah.class.violet for instance?

**Comment by prmr** [comment]
Yes, correct.

**Comment by JoelChev** [comment]
I believe I have succeeded in adding a diagram type file extension to saved files. Please check out branch extended_file_extension and play around with saving & loading files. I haven't written any tests, but it seems to work on my end. I haven't tested it without the serialization removed (which Martin did recently) though, so testing a later merged branch could also be useful.

**Comment by prmr** [comment]
There's a piece missing for managed file type descriptions in the file chooser. It does not regognize specific extension types. Have a look at how 0.21 does it. It recognizes specific diagram types, and also a generic "All violet files" for anything ending in .violet

**Comment by prmr** [comment]
I need to change `EditorFrame` as part of issue #26 so I'll wait until you integrate your brand into master before starting with this. BTW don't forget to name your branch according to the naming convention.

**Comment by JoelChev** [comment]
@prmr I see what you mean. I will look at it today and tomorrow and try to put that feature in. Thanks for pointing it out!

**Comment by JoelChev** [comment]
Ok, I just added the features that you outlined above @prmr. I didn't implement any tests for this, but when I played around with saving and opening files, the new diagram-specific extensions seemed to be behaving as they would in 0.21. If you guys can please check out this branch and test it for yourself, I would appreciate it. 

An important note however is that by changing the FileService class in this recent commit, I started to see errors in the JNLPFileService class. @EJBQ  this appears to be a class involved with Java Web Start, so as you are removing this the error shouldn't be an issue for our purposes. If it is please let me know and I can look into correcting the code in JNLPFileServices too.

**Comment by EJBQ** [comment]
@JoelChev The class is deleted, so those shouldn't come up. It's gone in master as well now.
