### ISSUE TITLE
Standardize Label Capitalization

### ISSUE THREAD

**Issue by prmr** [prmr/Violetta#25]
Current GUI conventions have Title Capitalization for menus and button labels.

**Comment by JoelChev** [comment]
@prmr Just to clarify, you want things like "Zoom in" to become "Zoom In" right?

**Comment by JoelChev** [comment]
@prmr Just to clarify, you want things like "Zoom in" to become "Zoom In" right?

**Comment by prmr** [comment]
yes

**Comment by JoelChev** [comment]
Alright, I have made a branch for this issue as well. I capitalized all of the menu items and all of the buttons (except for <<extend>> and <<include>> in Use Case Diagrams). Again, I couldn't think of a way to test this, so if you guys can please check out this branch and just make sure everything is capitalized properly I would appreciate it. Thanks!

**Comment by EJBQ** [comment]
I just looked through this. The only thing I still see other than what you mentioned is the dialog boxes in the properties menus. (e.g. "name", "attributes", "methods") I know it's convention for it to be lowercase in the code, but these do face the user and might be good to capitalize somehow, either in code or by converting to Title Case before showing.

**Comment by prmr** [comment]
I would prefer if we capitalized in the GUI, not in the code.

**Comment by JoelChev** [comment]
@EJBQ I just added a new method to the PropertyEditor class that parses Strings and converts them to a Title Form. By calling this method, I am able to make the properties in the diagrams capitalized. With this, the issue should be solved. I will merge and close this shortly.
