### ISSUE TITLE
Remove support for Java Web Start

### ISSUE THREAD

**Issue by prmr** [prmr/Violetta#6]
We won't be supporting this mode.

**Comment by EJBQ** [comment]
There's a line at UMLEditor.java:41 about an OSX feature that I can't tell if it's used locally on machine or not. SecurityExceptions elsewhere all seem to refer to Web Start, but I don't know about this one. I'm not on a Mac, so I don't know if there's special functionality there. I'm going to try getting a friend to run versions with and without the line and screenshot it.

**Comment by prmr** [comment]
I'm guessing the `apple.laf` property has to do with the look and feel and not Java Web Start, but it would be go to trace that through on a Mac sometimes out of curiosity. Actually I'm removed this line as part of issue #26.

**Comment by EJBQ** [comment]
@prmr So the line is definitely about the look and feel. Using it without the try/catch works fine, it moves the File and Edit and other menus up to the top bar, as with most OSX applications. If you remove the entire thing then the menus are inside the application. It might be worth asking Mac users which would be better.

**Comment by EJBQ** [comment]
The relevant classes, methods, and lines are all gone now.

**Comment by EJBQ** [comment]
Fixed by commits
853142f620e5dd8ef9b6ad94d3db49b4a8f738b9
34fc1df963c3b272ac52c74168b4c82e0d7aee54
0ad61022842dd3ff234ffac2700b5ba0649f3d28
